### ISSUE TITLE
How to use the model to predict

### ISSUE THREAD

**Issue by BLAIR-wy** [DS3Lab/DocParser#13]
I want to ask if I want to use this model to classify some new pages, where should I put my data?

**Comment by j-rausch** [comment]
Hey, the code snippet in this issue should be sufficient for that:
https://github.com/DS3Lab/DocParser/issues/7#issuecomment-717189426

**Comment by BLAIR-wy** [comment]
Thanks for your reply, but I couldn't find the detector component? And where should I add this code? where is the entity_detector comes from, I can't find this py file.
Could you give a more specific guidance of how to use the pretained model?
Thanks a lot!

**Comment by j-rausch** [comment]
I think a good entry point would be the demo code in https://github.com/DS3Lab/DocParser/blob/master/demos/demo_inference.py.
You can find an example for initializing the entity detector here: https://github.com/DS3Lab/DocParser/blob/master/demos/demo_inference.py#L279
There are some pretrained models that you can use, and using the option `default_weights="highlevel_wsft"` when initializing the model should usually give you the best performance.
