### ISSUE TITLE
[Question] Unexpected results when running on custom PDF files

### ISSUE THREAD

**Issue by WhoAteDaCake** [DS3Lab/DocParser#16]
Hello, thank you for the effort you've put into this repository. I've recently tried to run it against my own pdfs (converted to images)

<details>
  <summary>Click here to see the image</summary>

![outputname-01](https://user-images.githubusercontent.com/16735813/107073782-b2cbca00-67df-11eb-82bf-503fd89533cc.png)
</details>

And this was result:

<details>
  <summary>Click here to see the image</summary>

![outputname-01](https://user-images.githubusercontent.com/16735813/107073812-be1ef580-67df-11eb-91e9-83fb6299377d.png)
</details>

My code to draw:

```python
import argparse
import json
import logging
import os
import cv2

import skimage.io

from docparser import stage1_entity_detector


image_name="outputname-01.png"
sample_img_path = "/home/ubuntu/projects/pdf-expirements/DocParser/images/{}".format(image_name)
output_dir = "/home/ubuntu/projects/pdf-expirements/DocParser/demos/output"

entity_detector = stage1_entity_detector.EntityDetector()
entity_detector.init_model(default_weights="highlevel_wsft")

sample_img = skimage.io.imread(sample_img_path)
results = entity_detector.predict(sample_img)

image = cv2.imread(sample_img_path)

shapes = []
for pred in results["prediction_list"]:
  box = pred["bbox_orig_coords"].tolist()
  label = pred["class_name"]
  score = pred["pred_score"]
  shapes.append({"box": box, "label": label, "score": score})

for shape in shapes:
  y1, x1, y2, x2 = shape["box"]
  image = cv2.rectangle(image, (x1, y1), (x2, y2), (255, 0, 0), 2)


cv2.imwrite("{}/{}".format(output_dir, image_name), image)
```

Most of the bounding boxes were drawn very incorrectly. Am I doing the drawing wrong, or does it not work with files, which contain a structure like this. ? Thank you for your time.

**Comment by j-rausch** [comment]
Hey, thanks for your interest in the project!
From the code you shared it looks like you generated the outputs with the default WS+FT model. Generally, I'd expect it to need to be finetuned on a small set of images from your custom dataset in order to produce higher accuracy predictions, if the domains are not sufficiently similar in appearance and style.
