### ISSUE TITLE
DocParser Inference

### ISSUE THREAD

**Issue by zokai** [DS3Lab/DocParser#7]
Is there an inference code to pass my own input document using your pre-trained model and get the detected tables output?

Thank you.

**Comment by j-rausch** [comment]
Hi,

You should be able to just pass an image to the detector component, e.g.:
```
#init entity detector
sample_img = skimage.io.imread(sample_img_path)
entity_predictions = entity_detector.predict(sample_img)
entity_detector.save_predictions_to_file(entity_predictions, output_dir, sample_img_name)
```

**Comment by BLAIR-wy** [comment]
Where is the detector component? And where should I add this code?  where is the entity_detector comes from, I can't find this py file.
Could you give a more specific guidance of how to use the pertained model?
Thanks a lot!
